### ISSUE TITLE
Need the ability to setup exclude paths as well.

### ISSUE THREAD

**Issue by patricknelson** [scottsb/puppet-clustersync#1]
It appears that there is no incorporation of the `exclude` parameter in the `csync2_serverset.cfg.erb` template. Currently we've got a infinite loop in `lsyncd` where each server will create a file in a certain sub-directory matching a specific name (e.g. `_resampled`) which needs to be excluded. So since all of them will create this file it will loop endlessly since it'll always be dirty on all of the servers.

I'll try submit a PR soon to cover this case.

**Comment by scottsb** [comment]
Merged fix. Thanks!
